### ISSUE TITLE
Breakfast Recipe: Blueberry Smoothie

### ISSUE THREAD

**Issue by julianagensh** [IntroToCode/Spring22_Recipes_Codemates5#2]
## 💬 Discussion topic

Let's Make A Blueberry Smoothie 

## ❗ Potential issues

-Do we have the equipment necessary?
-Allergies
-Do we have time to make this?
-What ingredients do I need to buy?

## 👥 People
@olgaklinger86 and @albirch to make recipe clearly organized
@Joy9251 to list ingredients
@lttlfld to create instructions
@johnnybt1 to create headline and list time to make this recipe
@julianagensh to make sure no one will have allergic reaction

@Joy9251 and @lttlfld to approve this project, as they are our bo$$e$

## 📃 Details

Acceptance Criteria:

- Clearly organized recipe
- Ingredients
- Instructions
- Time to make
- Make sure to list allergy warnings

Operation time to create this recipe on Github
- Medium project

**Comment by lttlfld** [comment]
This recipe looks great - https://www.loveandlemons.com/blueberry-smoothie/
